allegro/ralph

.travis.yml
setup.py
src/ralph/settings.py

Movement device locations into `ralph_assets` and others caused a situation in which Ralph required `ralph_assets`.
Required: https://github.com/allegro/ralph_assets/pull/552

Ralph required ralph_assets package

---

src/ralph/cmdb/models_ci.py
src/ralph/cmdb/tests/unit/tests_ci.py

From now on, each newly  created CI is have ACTIVE state.

Set CI.state default value to ACTIVE

---

src/ralph/discovery/models_device.py
src/ralph/settings.py
src/ralph/util/models.py

The actual behavior of `Device.save()` is rather confusing, mostly because of the `SavePrioritized` mixin (some changes are silently dropped, which is hard to track if you're unaware of this mechanism) - therefore, I think it's good to provide some explaination for this in the source code.
Also, I've improved the description of `SyncFieldMixin` and moved some hard-coded stuff to settings.

minor improvements related to SyncFieldMixin and Device.save()

---

src/ralph/ui/templates/ui/device_info.html
src/ralph/ui/templates/ui/scan-list.html
src/ralph/ui/templates/ui/scan-status.html
src/ralph/ui/templates/ui/scan.html
src/ralph/ui/views/common.py

Currently, If you scan some device, you get the scan results without the possibility to easily go back to such device's info tab (except from going back to the main page and manually searching this device, which is rather tedious and annoying). This pull request addresses this by adding a convenient "Go to initial device view" button, which appears when scanned device's IP address is already linked to some device (otherwise it doesn't make sense, though).

Added 'Go to initial device view' button to scan results.

---

src/ralph/ui/static/partials/data_center/data_center_view.html
src/ralph/ui/static/partials/data_center/rack.html
src/ralph/ui/static/ui/css/data_center.css
src/ralph/ui/static/ui/css/data_center.less
src/ralph/ui/static/ui/css/rack.css
src/ralph/ui/static/ui/css/rack.less
src/ralph/ui/static/ui/js/app/apps.js
src/ralph/ui/static/ui/js/app/data_center/controllers.js
src/ralph/ui/static/ui/js/app/data_center/directives.js
src/ralph/ui/static/ui/js/app/data_center/services.js
src/ralph/ui/static/ui/js/app/rack/services.js

Changes:
- added modes - ``preview`` and ``edit``
- preview mode:
- no changes,
- edit mode:
- each rack can be move by drag and drop method
- drag and drop validation
- each rack can be rotate
- name and description of each rack can be edited

Added edit mode to data center view

---

.travis.yml
setup.py

according to django bugfix releases: https://www.djangoproject.com/weblog/2015/jan/13/security/
bumped django version to 1.4.18 (with additional bump in travis builds to 1.6.10)

bumped django version to 1.4.18

---

src/ralph/ui/templates/ui/base.html

Change the order of loading ajax_select.js file. 
jquery_ui.js loaded from ajax_select.js must be loaded before the bootstrap.js, another order causes error.

Fix button toogle on scan form.

---

src/ralph/discovery/admin.py
src/ralph/discovery/tests/test_admin.py

Parent and management fields are now readonly when an asset is assigned. Before this change we could't save form.

Fix in device admin panel.

---

src/ralph/scan/plugins/idrac.py
src/ralph/scan/tests/plugins/samples/idrac.py

For some configurations IDRAC plugin does not work because an error in MAC detecting function occurs. This function was changed to provide more stable detection. Also our tests sample data was updated.

Fix for MAC detecting in IDRAC plugin.

---

src/ralph/scan/plugins/puppet.py

Xen dom0 should be classified as physical machine:
xen3:~☠ facter -p  |grep -P '(virtual|^productname)' 
is_virtual => false
productname => IBM System x3550 -[7978ZBX]-
virtual => xen0
btw. is there a reason fact 'is_virtual' is not used for that ? Both facts come from same place ( https://github.com/puppetlabs/facter/blob/master/lib/facter/virtual.rb ).

Xen dom0 is incorrectly classified as virtual host

---

src/ralph/scan/plugins/ssh_cisco_catalyst.py
src/ralph/scan/tests/plugins/test_ssh_cisco_catalyst.py
src/ralph/util/network.py

* New connector added - CiscoSSHHandler
* Change ssh_cisco_catalyst_plugin to use new connetor
* ssh_cisco_catalyst_plugin now does not send `terminal length` command - it's now handled by connector class

New CiscoSSHHandler added to provide better support for Cisco switches.

---

src/ralph/ui/static/partials/rack/device_types/asset.html
src/ralph/ui/static/partials/rack/listing.html
src/ralph/ui/static/partials/rack/rack.html
src/ralph/ui/static/partials/rack/rack_view.html
src/ralph/ui/static/ui/css/rack.css
src/ralph/ui/static/ui/css/rack.less
src/ralph/ui/static/ui/js/app/rack/controllers.js
src/ralph/ui/static/ui/js/app/rack/directives.js

Motivation:
Visualization doesn't have link to core device (only to assets).
Changes:
* info box now contains links to core and assets
* change info box update behaviour (click instead of mouseover)
* highlighted U position

Added links to info box

---

src/ralph/ui/views/common.py

Prevent error when management IP is ``None``

Fixed 500 error when managment IP is blank

---

src/ralph/ui/widgets.py

Widgets shouldn't paste "None" string as a value when value is None -
empty string is much better. Previous behavior produce many validation
errors. E.g. IntegerField validation said that it's not a number -
that's right because "None" it is not a number :)

Fixed ReadOnlyWidget and ReadOnlySelectWidget

---

src/ralph/settings.py

Some settings must be put before pluggable apps initialization. If not,
then the plugins that use ralph will crash trying to import things from
ralph.

Moved the settings in settings.py

---

src/ralph/discovery/http.py
src/ralph/discovery/tests/test_http.py
src/ralph/scan/plugins/ssh_xen.py

The Xen servers > 6.5 don't contain 'xen' string in their snmp_name. We
need to detect them using their HTTP response (looking for 'XenServer'
string in the returned HTML document).
Also - renamed the existing Dell detection test, so new tests can be
added.

Improved Xen detection

---

src/ralph/app.py
src/ralph/ui/views/common.py

Some apps might not need an entry in menu or their own views (and hence
their own urls.py). This fix will cause them not to crash.

Allowed ralph plugins without menu entry and urls

---

src/ralph/cmdb/api.py
src/ralph/cmdb/importer.py
src/ralph/cmdb/integration/lib/jira.py
src/ralph/discovery/models_device.py
src/ralph/discovery/tests/test_models.py
src/ralph/ui/views/common.py
src/ralph/ui/views/racks.py
src/ralph/util/models.py
src/ralph/util/tests/utils.py

We want to set device properties from other places than just save() of
the device form. Thus we move the logic to a separate function.

Moved property setting to a separate function

---

src/ralph/settings.py

Before, DEFAULT_REGION_NAME (and SYNC_FIELD_MIXIN_NOTIFICATIONS_WHITELIST) was
below code loading ~/.ralph/settings which disallows change
DEFAULT_REGION_NAME (and SYNC_FIELD_MIXIN_NOTIFICATIONS_WHITELIST) in
~/.ralph/settings.
This change fixes that

Fixed settings position in settings file.

---

src/ralph/deployment/plugins/change_status.py
src/ralph/deployment/plugins/clean.py
src/ralph/deployment/plugins/dhcp.py
src/ralph/deployment/plugins/dns.py
src/ralph/deployment/plugins/role.py
src/ralph/deployment/tests/plugins/test_clean.py

Added clean plugin as required to each other plugins to make sure that
new venture and role will be assigned to deployed server.
Removed venture and role assignation form clean plugin - it's now not
required.

Changes in deployments plugins order.

---

src/ralph/ui/forms/addresses.py
src/ralph/ui/templates/ui/device_addresses.html
src/ralph/ui/tests/unit/test_fields.py
src/ralph/ui/views/common.py

The IPWithHostname field should always require IP Address, or else the
IPAddress object creation will fail.

Validation for IPWithHostnameField

---

Makefile

This fix is only for few days. Everything need back to old version when graph core will release as pypi package.

Fix install python-graph

---

src/ralph/settings.py

This changed prevented error like ``Cannot add or update a child row: a
foreign key constraint fails ... FOREIGN KEY (`content_type_id`) REFERENCES
`django_content_type` (`id`))'``.

Changed order in INSTALLED_APPS

---

Makefile
doc/installation.rst

Now python-graph-core package is hosted on https://pypi.python.org/

Remove workaround for installation python-graph-core

---

src/ralph/cmdb/integration/sync.py

There is no need to convert this to set, as [None] == [None]. On the
other hand lists are not hashable, so this crashes with new plugin

Corrected the check

---

.travis.yml
src/ralph/account/ldap.py
src/ralph/account/tests/test_models.py

Prevent error like ``UnicodeEncodeError: 'ascii' codec can't encode
character``.

Fixed unicode error and empty country by default

---

src/ralph/account/admin.py
src/ralph/account/models.py
src/ralph/settings.py

Basically nobody analyzes traffic in Ralph by lck.activitylog. This change
reduce number of DB queries about 12 per each request.

Removed lck.activitylog from Ralph

---

Makefile
doc/installation.rst
src/ralph/discovery/tests/util.py
src/ralph/util/demo/__init__.py
src/ralph/util/demo/assets/__init__.py
src/ralph/util/demo/assets/assets.py
src/ralph/util/demo/assets/dc_models.py
src/ralph/util/demo/assets/supports.py
src/ralph/util/demo/core/__init__.py
src/ralph/util/demo/core/cmdb.py
src/ralph/util/demo/core/discovery.py
src/ralph/util/management/commands/make_demo_data.py

I added new CLI command. Now, if you want to generate some example data use
``ralph make_demo_data``.
Available params for command:
- --flush - flush the databases,
- -d - execute fixture.
Example of use:
- ``ralph make_demo_data --flush -d envs -d services`` - flush databases and execute defined fixtures
- ``ralph make_demo_data --flush`` - interactive mode.

Added mechanism for generate demo data

---

src/ralph/discovery/tests/util.py
src/ralph/util/demo/core/discovery.py

Improvement demo data - now you can scan without any extra actions like added
new device model or assign model to device.

Added RackServerModelFactory to test's utils

---

src/ralph/ui/tests/unit/test_others.py
src/ralph/ui/views/common.py

Getting default pool's name only if pool is assigned.
@andrzej-jankowski

Fixed getting name of default pool for vserv.

---

src/ralph/scan/plugins/ssh_cisco_catalyst.py

Because of 'while True' in CiscoSSHHandler, on Juniper devices plugin sometimes sends command and waits for Cisco specific prompt forever. Checking if device is Juniper switch avoids this behavior.
Searching for 'cisco' in SNMP name can be another way to solve this problem but then we 'lose' switches with proper SSH configuration and some SNMP issues.

Juniper devices ignored in Cisco plugin scan

---

src/ralph/ui/views/common.py

Home view raised 500 because ``submodule_name`` was empty.

Added ``submodule_name`` to Home view
