src/ralph/ui/static/partials/rack/pdu_item.html, src/ralph/ui/static/partials/rack/rack.html, src/ralph/ui/static/partials/rack/rack_view.html, src/ralph/ui/static/ui/css/rack.css, src/ralph/ui/static/ui/css/rack.less, src/ralph/ui/static/ui/js/app/rack/directives.js
Changes:
- added directive (``pdu-item``) responsible for correct display of PDU,
- added ``.pdu .item`` class to CSS.
=> Fixed correct PDU visualization

src/ralph/discovery/tests/util.py
Added a few new factories needed to fixturing demo version.
=> Added new factories.

.travis.yml
Changes:
- now Travis CI test project on MySQL, SQLite with two different Django version.
=> Change build matrix in Travis

doc/configuration.rst, src/ralph/context_processors.py, src/ralph/settings.py, src/ralph/ui/templates/ui/base.html
Allows tracking code from providers such as: Google Analytics, Piwik etc.
Reopened PR: https://github.com/allegro/ralph/pull/1251
=> [Reopened] Functionality allows inject custom tracking code

src/ralph/scan/util.py, src/ralph/ui/templates/ui/scan-list.html, src/ralph/ui/views/common.py
This pull request fixes broken display of results in the 'Pending Scans' view (changes marked as 'new' were also displayed on the 'existing' tab).
=> Fixes for 'pending scans' view.

src/ralph/ui/templates/ui/scan.html, src/ralph/ui/tests/functional/tests_scan.py, src/ralph/ui/views/common.py
Earlier when scan IPAddressed which does not exist in database, it was necessary to add it manually through the admin panel. 
Now, the scan view create automatically IPAddress when does not exist in database.
=> Scan form create IPAddress object when does not exist.

src/ralph/ui/static/partials/data_center/data_center_view.html, src/ralph/ui/static/ui/css/data_center.css, src/ralph/ui/static/ui/css/data_center.less, src/ralph/ui/static/ui/js/app/data_center/controllers.js
Changes:
- data center grid respect values returned by API.
Related bug: https://github.com/allegro/ralph/issues/1270
=> Fixed update dimensions

src/ralph/discovery/tests/util.py, src/ralph/util/api_scrooge.py, src/ralph/util/tests/tests.py
added databases to scrooge api to show them as components in scrooge components view and to make ability to charge for single database server.
=> added database to scrooge api

src/ralph/ui/static/partials/data_center/data_center_view.html, src/ralph/ui/static/ui/css/rack.css, src/ralph/ui/static/ui/css/rack.less, src/ralph/ui/static/ui/js/app/data_center/directives.js
Changes:
- deleted rotate barcode for slim slots,
- fixed bug in Firefox - very tiny input box in edit mode,
- rotate action run ``$update``.
=> Fixed few bugs in edit mode.

src/ralph/deployment/tests/functional/tests_api.py
Just a set of testcase renames to comply with our policies. Should clean up the Andrzej's PR.
=> Renamed tests to comply with test/should/when

src/ralph/deployment/api.py, src/ralph/deployment/tests/functional/tests_api.py, src/ralph/deployment/tests/test_util.py, src/ralph/deployment/util.py, src/ralph/dnsedit/tests/util.py, src/ralph/urls.py
* Added new API entry point - /api/v0.9/change-ip-address/
* Reason: Possibility to change IP address after server deployment.
=> Added new entry point to API to provide possibility to change IP address

src/ralph/ui/static/ui/css/data_center.css, src/ralph/ui/static/ui/css/data_center.less, src/ralph/ui/static/ui/css/rack.css, src/ralph/ui/static/ui/css/rack.less, src/ralph/ui/static/ui/css/variables.less
Changes:
* changed position property to info box
* added border to info box
=> Cosmetic changes to info box

src/ralph/ui/static/ui/css/rack.css, src/ralph/ui/static/ui/css/rack.less
Changes:
* added style for style in 3U chassis
=> Added style for style in 3U chassis

src/ralph/ui/static/ui/js/app/apps.js, src/ralph/ui/static/ui/js/app/data_center/directives.js, src/ralph/ui/templates/ui/base.html, src/ralph/ui/templates/ui/data_center_view.html, src/ralph/ui/templates/ui/racks_rack.html
Changes:
* include angular scripts if necessary
* reduced requests when user rotate rack
* removed unused device.css
* small refactor of variables name
=> Visualization improvments

src/ralph/ui/static/ui/css/rack.css, src/ralph/ui/static/ui/css/rack.less
Changes:
* added layouts 2x4 and 2x6
=> Added extra layouts for visualization

installation.html
It's hard to install Ralph by hand, so i added the Docker way
explanation.
=> Updated the installation with cautions.

src/ralph/deployment/tests/functional/tests_api.py, src/ralph/ui/tests/global_utils.py, src/ralph/ui/views/deploy.py
You need core access to create a VM via API.
=> Changed the required permission for VM creation

src/ralph/discovery/admin.py, src/ralph/discovery/tests/test_admin.py, src/ralph/ui/forms/addresses.py, src/ralph/ui/templates/ui/device_addresses.html, src/ralph/ui/templates/ui/ip_with_host_widget.html, src/ralph/ui/views/common.py
I added form where admins can edit IP management from device edit view in core.
=> Added editable management IP in 'Addresses' tab

src/ralph/ui/forms/search.py, src/ralph/ui/views/search.py
=> Added department to search form

src/ralph/ui/tests/global_utils.py, src/ralph/util/tests/utils.py
The CMDB use own UserFactory and UserFactory from /ui/tests/global_utils.py.
For this reason each factory have own sequence.
=> Removed duplicated UserFactory

src/ralph/ui/templates/ui/device_addresses.html
Changes:
* removed if statment from template
* form hs moved to top
=> Management IP form always visible

src/ralph/deployment/plugins/clean.py, src/ralph/deployment/tests/plugins/test_clean.py, src/ralph/ui/tests/functional/tests_bulkedit_form.py, src/ralph/util/tests/utils.py
* The hostname is now copied from deployment
* Also copying venture/role from deployment
* Factories for venture/role moved to utils
=> Added two missing features to deploy/clean plugin

src/ralph/scan/data.py, src/ralph/scan/forms.py
* Added model_type to columns in subdevices
* Subdevice creation is done with priority=215
* Handled asset=None situation
=> Corrections for scan confirmation

src/ralph/scan/data.py
Previously only physical subdevices not found by scan were detached.
Extended this feature on logical children
=> Detaching logical subdevices not found by scan

src/ralph/cmdb/forms.py, src/ralph/cmdb/importer.py, src/ralph/cmdb/models_signals.py, src/ralph/cmdb/util.py, src/ralph/cmdb/views_changes.py, src/ralph/discovery/management/commands/report.py, src/ralph/ui/views/search.py
In new version of pep8 (1.6.2) raise W503 as error.
=> Fixed W503

src/ralph/deployment/tests/test_util.py, src/ralph/deployment/tests/utils.py, src/ralph/deployment/util.py, src/ralph/discovery/tests/util.py, src/ralph/ui/forms/deployment.py, src/ralph/ui/tests/functional/test_mass_deployment.py, src/ralph/ui/urls.py
Service and environment are required when using mass deploy form.
=> Added service and environment to mass deploy

src/ralph/scan/postprocess/lldp_connections.py
To prevent raise `UnboundLocalError`.
=> Added default value to connection variable

setup.py
Pytz packaged upgraded to version=2013.6.
=> Upgraded pytz package.

src/ralph/scan/plugins/ssh_juniper.py, src/ralph/scan/tests/plugins/test_ssh_juniper.py
Changes in Juniper SSH scan plugin to distinguish between different device models in stack.
=> better scan of Juniper stacks

src/ralph/ui/static/partials/rack/device_types/asset.html, src/ralph/ui/static/partials/rack/rack_view.html, src/ralph/ui/static/ui/css/rack.css, src/ralph/ui/static/ui/css/rack.less
List of changes:
- Service Catalog, Hostname and Management IP address are now display in
Info Box on the left
- Service Catalog and hostname are now display on rack visualisation
(instead of model)
- Minor CSS changes.
Depends on: https://github.com/allegro/ralph_assets/pull/605
=> Rack Visualisation view changes.

src/ralph/ui/templates/ui/base.html
Some responsive features for Ralph, only for mobile app.
Requires: https://github.com/allegro/django-bob/pull/56
=> Responsive Ralph design

src/ralph/ui/static/partials/rack/device_types/accessory.html, src/ralph/ui/static/partials/rack/rack_view.html, src/ralph/ui/static/ui/css/rack.css, src/ralph/ui/static/ui/css/rack.less, src/ralph/ui/static/ui/js/app/rack/controllers.js, src/ralph/ui/static/ui/js/app/rack/directives.js
Changes list:
- remarks are now display on patch panel
- patch pannels are now clickable
- link to rack edit panel was added to info box
Patch Panel visualization:
Infobox for patch pannels:
Depends on: https://github.com/allegro/ralph_assets/pull/611
=> Patch pannels visualization changes.

src/ralph/ui/static/partials/data_center/data_center_view.html, src/ralph/ui/static/partials/data_center/rack.html, src/ralph/ui/static/partials/rack/device_types/asset.html, src/ralph/ui/static/partials/rack/rack_view.html, src/ralph/ui/static/ui/css/data_center.css, src/ralph/ui/static/ui/css/data_center.less, src/ralph/ui/static/ui/css/rack.css, src/ralph/ui/static/ui/css/rack.less, src/ralph/ui/static/ui/css/variables.less, src/ralph/ui/static/ui/js/app/data_center/controllers.js, src/ralph/ui/static/ui/js/app/data_center/directives.js, src/ralph/ui/static/ui/js/app/rack/directives.js
* The racks get narrower on narrow monitors
* The hover/activation is uniformly done with a white border
* The borders in info table are corrected (removed extra border under
last element.
=> Various tweaks for visualization

.gitignore
Adding new files to .gitignore
=> Change .gitignore config

src/ralph/ui/static/ui/css/rack.css, src/ralph/ui/static/ui/css/rack.less
Fixed mistake (:hover instead of :over).
=> Improvements of CSS

src/ralph/ui/static/partials/rack/device.html, src/ralph/ui/static/partials/rack/device_item.html, src/ralph/ui/static/partials/rack/device_types/accessory.html, src/ralph/ui/static/partials/rack/device_types/asset.html, src/ralph/ui/static/partials/rack/rack.html, src/ralph/ui/static/partials/rack/rack_view.html, src/ralph/ui/static/ui/css/data_center.css, src/ralph/ui/static/ui/css/rack.css, src/ralph/ui/static/ui/css/rack.less, src/ralph/ui/static/ui/js/app/rack/directives.js
Added visualization rear of chassis.
=> Added new layout in CSS and adpat front to new API

src/ralph/ui/static/partials/rack/device_types/asset.html
This mistake caused by refactoring (PR #1335).
=> Changed function name to setActiveItem instead of setActiveDevice

src/ralph/ui/templates/ui/device_addresses.html
Removed redundant button in the form + added submit name to the form so that
view can save the form (view checks for specific name in request to save it)
Depends on:
https://github.com/allegro/django-bob/pull/57
=> Fixed 'Management address' in form of Addresses tab.

doc/installation.rst
Change Docker instalation documentation for new ralph image.
=> Change Ralph install docker documentation

doc/installation.rst
Adding the mac address to the installation documentation for Ralph Docker quick scan test.
=> Add mac address to ralph docker documentation

src/ralph/account/management/commands/ldap_sync.py, src/ralph/account/tests/test_models.py
Before, ldap users with surname longer then 30 (Django's default) chars break
synching. Now such surnames are truncated to 30 chars.
=> Truncate too long surnames when synchronising users with ldap.

src/ralph/ui/views/common.py
Fixed 500 status response when bulkedit in core
=> Fixed 500 status response when bulkedit in core

src/ralph/cmdb/templates/cmdb/report_changes.html
Restore pagination on CMDB changes subpage
=> Restore pagination on CMDB changes subpage

src/ralph/ui/static/ui/css/rack.css, src/ralph/ui/static/ui/css/rack.less
Removed side borders, left only top and bottom borders - highlight is
still visible but no flaw.
@ar4s
=> Fixed highlighting elements on hover in visualization.

src/ralph/scan/data.py
Ignore connections to deleted device when save scan results.
=> Get only connections to non deleted devices

src/ralph/util/demo/core/cmdb.py, src/ralph/util/demo/core/discovery.py
=> Added networks to fixtures

doc/installation.rst
Change ralph documentation docker init
=> Change ralph documentation

src/ralph/util/demo/core/cmdb.py, src/ralph/util/demo/core/discovery.py
=> Added new relations for business line and profit center

src/ralph/util/demo/assets/supports.py
=> Unpack list of blade_servers

src/ralph/util/demo/assets/assets.py
=> Added service_name to demo

doc/installation.rst
Change -name to --name in ralph install documentation
=> Change -name to --name in ralph install documentation

src/ralph/util/demo/assets/supports.py
Now demo data generate 11 licences.
=> Incremented number of generated licence in demo data

src/ralph/cmdb/tests/utils.py
Now factory return object with human readable name.
=> Changed name for DeviceEnvironmentFactory and ServiceCatalogFactory

src/ralph/util/demo/assets/assets.py
=> Added power_consumption and invoice_date

src/ralph/discovery/tests/util.py, src/ralph/util/demo/assets/assets.py, src/ralph/util/demo/core/cmdb.py, src/ralph/util/demo/core/discovery.py
* added VIP, Database, Virtual and Tenant to demo data
* minor tweaks in other demo data classes
=> Demo data: VIP, Database, Virtual and Tenant

src/ralph/menu.py, src/ralph/util/demo/core/discovery.py
* added back networks to top menu with option to hide it using HIDE_MENU settings
* changed default networks in demo data
* added subnetwork to demo data
=> Network tweaks

setup.py, src/ralph/util/management/commands/make_demo_data.py
Changed method to load demo date from entry points.
=> Fixed scanning entry points for demo data

src/ralph/ui/views/common.py
Decorated post method in ScanStatus view with @commit_on_success to prevent
partial save of data.
=> Added @commit_on_success to post form in ScanStatus

Makefile, src/ralph/cmdb/templates/cmdb/base.html, src/ralph/cmdb/templates/cmdb/graphs.html, src/ralph/cmdb/templates/cmdb/timeline.html, src/ralph/media/css/ventures.css, src/ralph/media/filtered_widget/style.css, src/ralph/settings-test-ralph.py, src/ralph/settings.py, src/ralph/templates/403.html, src/ralph/ui/templates/ui/angular_scripts.html, src/ralph/ui/templates/ui/base.html, src/ralph/ui/templates/ui/data_center_view.html, src/ralph/ui/templates/ui/racks_rack.html, src/ralph/ui/templates/ui/scan-status.html, src/ralph/ui/templates/ui/scan.html, src/ralph/ui/templates/ui/ventures-venture.html
Main changes:
* md5 hash of content in file name
* replace {{ STATIC_URL }} by templatetag {% static 'foo/bar.css' %} from ``staticfiles``
For more information please visit https://docs.djangoproject.com/en/1.4/ref/contrib/staticfiles/#django.contrib.staticfiles.storage.CachedStaticFilesStorage
=> Versioning static files

src/ralph/cmdb/templates/cmdb/base.html, src/ralph/ui/templates/ui/data_center_view.html, src/ralph/ui/templates/ui/racks_rack.html
Prevented exception like ``SuspiciousOperation``.
=> Removed slash at begin in static's URL

.travis.yml, Makefile
* linter detect missing `trans` tag in *.html files.
=> New: Django i18n template linter added in .travis.yml.
